# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Backslash 21st 
tagline:          "Wandering with the programming art"
description:      'Thoughts of a developer wandering far in the binary world. Eternal student of <a href="https://en.wikipedia.org/wiki/Bak_Mei">Pai Mei</a> programming style and its Five-Point Palm Exploding Heart Technique.'
url:              http://llh1.github.io
baseurl:          /

author:
  name:           'Loic Le Henaff'
  url:            http://llh1.github.io

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/llh1/

linkedin:
  url:            https://cn.linkedin.com/in/loiclehenaff
